import type { SealConfig } from '../types'

export type TemplatePreset = SealConfig

const baseDefaults: Partial<SealConfig> = {
  diameter: 400,
  rotation: 0,
  backgroundColor: 'transparent',
  fontFamily: 'serif',
  centerSymbol: 'star',
  starPoints: 5,
  serialNumber: '',
  centerText: '',
  borderStyle: 'solid',
  microText: '',
  microTextFontSize: 8,
  uploadedImage: null,
}

export const chineseTemplates: TemplatePreset[] = [
  {
    ...baseDefaults,
    id: 'gongzhang',
    name: '企业公章',
    shape: 'circular',
    borderColor: '#CC0000',
    outerBorderWidth: 6,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: '合肥弗兰克国际贸易有限公司',
    bottomText: '公章',
    centerText: '',
    centerSymbol: 'star',
    starPoints: 5,
    serialNumber: '91340100MA2XXXXXXX',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 40,
    bottomFontSize: 26,
    centerFontSize: 20,
    serialFontSize: 13,
    microText: '★弗兰克★',
    microTextFontSize: 9,
    uploadedImage: null,
    diameter: 400,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'hetong',
    name: '合同专用章',
    shape: 'circular',
    borderColor: '#CC0000',
    outerBorderWidth: 6,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: '合肥弗兰克国际贸易有限公司',
    bottomText: '合同专用章',
    centerText: '',
    centerSymbol: 'star',
    starPoints: 5,
    serialNumber: '91340100MA2XXXXXXX',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 38,
    bottomFontSize: 22,
    centerFontSize: 20,
    serialFontSize: 13,
    microText: '★合同专用★',
    microTextFontSize: 9,
    uploadedImage: null,
    diameter: 400,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'caiwu',
    name: '财务专用章',
    shape: 'circular',
    borderColor: '#CC0000',
    outerBorderWidth: 6,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: '合肥弗兰克国际贸易有限公司',
    bottomText: '财务专用章',
    centerText: '',
    centerSymbol: 'star',
    starPoints: 5,
    serialNumber: '',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 38,
    bottomFontSize: 22,
    centerFontSize: 20,
    serialFontSize: 13,
    microText: '★财务专用★',
    microTextFontSize: 9,
    uploadedImage: null,
    diameter: 380,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'fapiao',
    name: '发票专用章',
    shape: 'elliptical',
    borderColor: '#CC0000',
    outerBorderWidth: 5,
    innerBorderWidth: 1.5,
    borderStyle: 'dashed',
    topText: '合肥弗兰克国际贸易有限公司',
    bottomText: '发票专用章',
    centerText: '91340100MA2XXXXXXX',
    centerSymbol: 'none',
    starPoints: 5,
    serialNumber: '',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 34,
    bottomFontSize: 22,
    centerFontSize: 14,
    serialFontSize: 12,
    microText: '',
    microTextFontSize: 8,
    uploadedImage: null,
    diameter: 420,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'farendaibiao',
    name: '法定代表人章',
    shape: 'square',
    borderColor: '#CC0000',
    outerBorderWidth: 3,
    innerBorderWidth: 0,
    borderStyle: 'solid',
    topText: '',
    bottomText: '',
    centerText: '张伟',
    centerSymbol: 'none',
    starPoints: 5,
    serialNumber: '',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 36,
    bottomFontSize: 20,
    centerFontSize: 48,
    serialFontSize: 12,
    microText: '',
    microTextFontSize: 8,
    uploadedImage: null,
    diameter: 200,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  // ── 新增模板 ──
  {
    ...baseDefaults,
    id: 'baoguan',
    name: '报关专用章',
    shape: 'elliptical',
    borderColor: '#003399',
    outerBorderWidth: 5,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: '合肥弗兰克国际贸易有限公司',
    bottomText: '报关专用章',
    centerText: '海关编码',
    centerSymbol: 'star',
    starPoints: 5,
    serialNumber: '3401960001',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 36,
    bottomFontSize: 22,
    centerFontSize: 14,
    serialFontSize: 14,
    microText: '',
    microTextFontSize: 8,
    uploadedImage: null,
    diameter: 420,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'jianyan',
    name: '检验专用章',
    shape: 'circular',
    borderColor: '#CC0000',
    outerBorderWidth: 6,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: '合肥弗兰克国际贸易有限公司',
    bottomText: '检验专用章',
    centerText: '',
    centerSymbol: 'star',
    starPoints: 5,
    serialNumber: 'QC-2024-001',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 38,
    bottomFontSize: 22,
    centerFontSize: 20,
    serialFontSize: 13,
    microText: '★检验专用★',
    microTextFontSize: 9,
    uploadedImage: null,
    diameter: 380,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'xiangmu',
    name: '项目专用章',
    shape: 'circular',
    borderColor: '#CC0000',
    outerBorderWidth: 6,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: '合肥弗兰克国际贸易有限公司',
    bottomText: '项目专用章',
    centerText: '',
    centerSymbol: 'star',
    starPoints: 5,
    serialNumber: 'XM-2024-088',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 38,
    bottomFontSize: 22,
    centerFontSize: 20,
    serialFontSize: 13,
    microText: '★项目专用★',
    microTextFontSize: 9,
    uploadedImage: null,
    diameter: 380,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'gonghui',
    name: '工会委员会',
    shape: 'circular',
    borderColor: '#CC0000',
    outerBorderWidth: 6,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: '合肥弗兰克国际贸易有限公司工会委员会',
    bottomText: '工会专用章',
    centerText: '',
    centerSymbol: 'star',
    starPoints: 5,
    serialNumber: '',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 34,
    bottomFontSize: 22,
    centerFontSize: 20,
    serialFontSize: 12,
    microText: '★工会专用★',
    microTextFontSize: 9,
    uploadedImage: null,
    diameter: 400,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'xuexiao',
    name: '学校公章',
    shape: 'circular',
    borderColor: '#CC0000',
    outerBorderWidth: 6,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: '合肥市第一中学',
    bottomText: '教务处',
    centerText: '',
    centerSymbol: 'star',
    starPoints: 5,
    serialNumber: '',
    fontFamily: '"SimSun", "STSong", "宋体", serif',
    topFontSize: 42,
    bottomFontSize: 26,
    centerFontSize: 20,
    serialFontSize: 12,
    microText: '★教务处★',
    microTextFontSize: 9,
    uploadedImage: null,
    diameter: 400,
    rotation: 0,
    backgroundColor: 'transparent',
  },
]

export const foreignTemplates: TemplatePreset[] = [
  {
    ...baseDefaults,
    id: 'corporate-seal',
    name: 'Corporate Seal',
    shape: 'circular',
    borderColor: '#003399',
    outerBorderWidth: 5,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: 'FRANK INTERNATIONAL TRADING',
    bottomText: 'CORPORATE SEAL',
    centerText: '2024',
    centerSymbol: 'none',
    starPoints: 5,
    serialNumber: '',
    fontFamily: '"Times New Roman", Georgia, serif',
    topFontSize: 30,
    bottomFontSize: 20,
    centerFontSize: 28,
    serialFontSize: 12,
    microText: '',
    microTextFontSize: 8,
    uploadedImage: null,
    diameter: 400,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'notary',
    name: 'Notary Public',
    shape: 'circular',
    borderColor: '#003399',
    outerBorderWidth: 5,
    innerBorderWidth: 0,
    borderStyle: 'solid',
    topText: 'STATE OF CALIFORNIA',
    bottomText: 'NOTARY PUBLIC',
    centerText: 'JOHN SMITH',
    centerSymbol: 'none',
    starPoints: 5,
    serialNumber: 'Comm. Exp. 2028',
    fontFamily: '"Times New Roman", Georgia, serif',
    topFontSize: 28,
    bottomFontSize: 22,
    centerFontSize: 24,
    serialFontSize: 14,
    microText: '',
    microTextFontSize: 8,
    uploadedImage: null,
    diameter: 400,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'common-seal',
    name: 'Common Seal (UK)',
    shape: 'circular',
    borderColor: '#CC0000',
    outerBorderWidth: 5,
    innerBorderWidth: 1.5,
    borderStyle: 'solid',
    topText: 'FRANK & CO. LIMITED',
    bottomText: 'COMMON SEAL',
    centerText: '',
    centerSymbol: 'star',
    starPoints: 5,
    serialNumber: '',
    fontFamily: '"Times New Roman", Georgia, serif',
    topFontSize: 28,
    bottomFontSize: 22,
    centerFontSize: 24,
    serialFontSize: 12,
    microText: '★COMMON SEAL★',
    microTextFontSize: 8,
    uploadedImage: null,
    diameter: 400,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'approved',
    name: 'Approved Stamp',
    shape: 'rectangular',
    borderColor: '#CC0000',
    outerBorderWidth: 3,
    innerBorderWidth: 0,
    borderStyle: 'solid',
    topText: 'APPROVED',
    bottomText: '',
    centerText: 'DATE: ____/____/____',
    centerSymbol: 'none',
    starPoints: 5,
    serialNumber: '',
    fontFamily: '"Times New Roman", Georgia, serif',
    topFontSize: 36,
    bottomFontSize: 20,
    centerFontSize: 20,
    serialFontSize: 12,
    microText: '',
    microTextFontSize: 8,
    uploadedImage: null,
    diameter: 350,
    rotation: 0,
    backgroundColor: 'transparent',
  },
  {
    ...baseDefaults,
    id: 'received',
    name: 'Received Stamp',
    shape: 'rectangular',
    borderColor: '#003399',
    outerBorderWidth: 3,
    innerBorderWidth: 0,
    borderStyle: 'solid',
    topText: 'RECEIVED',
    bottomText: '',
    centerText: 'DATE: ____/____/____',
    centerSymbol: 'none',
    starPoints: 5,
    serialNumber: '',
    fontFamily: '"Times New Roman", Georgia, serif',
    topFontSize: 36,
    bottomFontSize: 20,
    centerFontSize: 20,
    serialFontSize: 12,
    microText: '',
    microTextFontSize: 8,
    uploadedImage: null,
    diameter: 350,
    rotation: 0,
    backgroundColor: 'transparent',
  },
]

export const allTemplates: TemplatePreset[] = [...chineseTemplates, ...foreignTemplates]
